#!/bin/sh
# Rewrite dist/setu.deps from the DECLARED [deps] stdlib in cyrius.cyml.
#
# ⛔ WHY THIS EXISTS. `cyrius distlib` generates `dist/setu.deps` and its own header calls it "stdlib
# leaves this fold requires in scope" — but it emits a fixed core subset that is neither the declared
# list nor a symbol closure. For setu it emits 8 while setu needs 12, silently dropping `result`,
# `net`, `chrono` and `args`. Measured three ways (see
# docs/development/issues/2026-08-07-distlib-deps-sidecar-under-reports.md): removing an entry from
# the declaration does not change it, an inline comment does not cause the drop, and the missing
# modules' symbols ARE referenced at top level in src/client.cyr.
#
# ⛔ A CONSUMER THAT TRUSTS THE SIDECAR BUILDS ON LINUX AND FAILS TO LINK `_agnos_getenv` ON AGNOS —
# in the consumer's repo, on the other target, with nothing pointing back here. Filing the cyrius
# defect does not protect anyone in the meantime; this does. setu owns dist/, so setu states the truth.
#
# Run after `cyrius distlib`. CI runs it and fails if it changed anything.
set -eu
cd "$(dirname "$0")/.."

DECLARED=$(python3 - <<'PY'
import re
s = open("cyrius.cyml", encoding="utf-8").read()
# [deps] stdlib = [ ... ] — entries may carry trailing # comments and span lines.
m = re.search(r'^\s*stdlib\s*=\s*\[(.*?)\]', s, re.S | re.M)
if not m:
    raise SystemExit("sync-deps-sidecar: no [deps] stdlib array in cyrius.cyml")
print("\n".join(re.findall(r'"([^"]+)"', m.group(1))))
PY
)

[ -n "$DECLARED" ] || { echo "sync-deps-sidecar: declared stdlib list is empty"; exit 1; }

{
    echo "# cyrius dep sidecar - stdlib leaves this fold requires in scope."
    echo "# Generated by scripts/sync-deps-sidecar.sh from [deps] stdlib in cyrius.cyml."
    echo "# NOT the raw \`cyrius distlib\` output: that under-reports (8 of 12 for setu) and drops"
    echo "# result/net/chrono/args. See docs/development/issues/2026-08-07-distlib-deps-sidecar-under-reports.md"
    echo "$DECLARED"
} > dist/setu.deps

echo "sync-deps-sidecar: $(echo "$DECLARED" | wc -l | tr -d ' ') leaves written to dist/setu.deps"
